#!/usr/bin/env ruby
#
# Very naive, very simple script to make XML files have one tag per line
#
# Run with no arguments for usage
#

if ARGV.empty?
  STDERR.puts "Usage: #{$0} [-i] <XML files...>"
  exit 1
end

if ARGV.any? { |arg| arg == '-i' }
  ARGV.delete '-i'
  ARGV.each { |filename|
    text = File.read(filename).gsub(/>\s*</, ">\n<")
    File.open(filename, 'w') { |f| f.puts text }
  }
else
  puts ARGF.read.gsub(/>\s*</, ">\n<")
end

